[package]
name = "op2paque"
version = "0.1.0"
edition = "2021"

[dependencies]
opaque-ke = {version = "3.0.0-pre.5", features = ["ristretto255", "argon2"]}
argon2 = {version = "0.5.0"}
rand = "0.8.5"
generic-array = {version = "1.1.0", features = ["serde"]}
serde = "1.0.210"
serde_json = "1.0.128"
