[package]
name = "op2paque"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = "0.10.1"
curve25519-dalek = { version = "4.1.3", features = ["serde"] }
rand = "0.8.5"
serde = "1.0.210"
serde_json = "1.0.128"
sha3 = "0.10.8"
signatures = "0.0.0"
voprf = { version = "0.5.0", features = ["serde"] }
